spring.application.name=flood-aid
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate properties (optional)
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

#Minio settings
#Cloudinary settings
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Max file size.
spring.servlet.multipart.max-file-size=20MB
# Max request size.
spring.servlet.multipart.max-request-size=30MB

server.tomcat.relaxed-query-chars=|,{,},[,]
line.channel.id=${LINE_CHANNEL_ID}

# OpenStreetMap static render settings
osm.static.zoom=18
osm.static.width=640
osm.static.height=480
osm.static.tile.url.template=https://tile.openstreetmap.org/%d/%d/%d.png
osm.static.user-agent=FloodAid/1.0 (+https://openstreetmap.org)
