#apiVersion: v1
#kind: Secret
#metadata:
#  name: app-secret
#  namespace: onspot
#type: Opaque
#data:
#  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMub25zcG90LnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvb25zcG90X2Ri
#  SPRING_DATASOURCE_USERNAME: cm9vdA==
#  SPRING_DATASOURCE_PASSWORD: c2VjcmV0
#  MINIO_ENDPOINT: aHR0cDovL21pbmlvLm9uc3BvdC5zdmMuY2x1c3Rlci5sb2NhbDo5MDAw
#  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==
#  MINIO_SECRET_KEY: bWluaW9hZG1pbjEyMw==

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: onspot
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vbm9uby1kYi5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb206NTQzMi9vbnNwb3QtZGI/c3NsbW9kZT1yZXF1aXJl
  SPRING_DATASOURCE_USERNAME: cmVodW50
  SPRING_DATASOURCE_PASSWORD: MDgwMTI4NDk3N05u
  MINIO_ENDPOINT: aHR0cDovL21pbmlvLm9uc3BvdC5zdmMuY2x1c3Rlci5sb2NhbDo5MDAw
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==
  MINIO_SECRET_KEY: bWluaW9hZG1pbjEyMw==