CREATE TABLE "locations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "latitude" decimal(10,8),
  "longitude" decimal(11,8),
  "address" varchar,
  "sub_district" varchar,
  "district" varchar,
  "province" varchar,
  "postal_code" varchar
);

CREATE TABLE "configs"(
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" varchar UNIQUE ,
  "value" varchar
);

CREATE TABLE "report_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar,
  "user_ordering_number" integer,
  "government_ordering_number" integer
);

CREATE TABLE "image_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "file_limit" int
);

CREATE TABLE "images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "image_category_id" integer,
  "report_id" integer,
  "phase" varchar -- 'BEFORE' or 'AFTER'
);

CREATE TABLE "reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid,
  "first_name" varchar,
  "last_name" varchar,
  "location_id" integer,
  "main_phone_number" varchar,
  "reserve_phone_number" varchar,
  "report_status_id" integer,
  "additional_detail" text,
  "after_additional_detail" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "report_assistances" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "report_id" integer,
  "assistance_type_id" integer,
  "quantity" integer,
  "is_active" boolean
);

CREATE TABLE "report_assistance_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "report_id" integer,
  "assistance_type_id" integer,
  "quantity" integer,
  "is_active" boolean
);

CREATE TABLE "assistance_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "unit" varchar
);

CREATE TABLE "users_admin" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "password" varchar,
  "created_at" timestamp
);

CREATE TABLE "provinces" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" int,
  "name_in_thai" varchar,
  "name_in_english" varchar
);

CREATE TABLE "districts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" int,
  "name_in_thai" varchar,
  "name_in_english" varchar,
  "province_id" int
);

CREATE TABLE "subdistricts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" int,
  "name_in_thai" varchar(150),
  "name_in_english" varchar(150) DEFAULT null,
  "latitude" decimal(10,8),
  "longitude" decimal(11,8),
  "district_id" int,
  "zip_code" int
);

CREATE INDEX "fk_locations_sub_district" ON "locations" ("sub_district");

CREATE INDEX "fk_images_report_id" ON "images" ("report_id");

CREATE INDEX "fk_reports_user_id" ON "reports" ("user_id");

CREATE INDEX "fk_report_assistances_report_id" ON "report_assistances" ("report_id");

CREATE UNIQUE INDEX ON "report_assistances" ("report_id", "assistance_type_id");

CREATE INDEX "fk_districts_province_id" ON "districts" ("province_id");

CREATE INDEX "fk_subdistricts_district_id" ON "subdistricts" ("district_id");

ALTER TABLE "reports" ADD FOREIGN KEY ("report_status_id") REFERENCES "report_status" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "report_assistances" ADD FOREIGN KEY ("report_id") REFERENCES "reports" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "report_assistance_logs" ADD FOREIGN KEY ("report_id") REFERENCES "reports" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "images" ADD FOREIGN KEY ("report_id") REFERENCES "reports" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "reports" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "report_assistances" ADD FOREIGN KEY ("assistance_type_id") REFERENCES "assistance_types" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "images" ADD FOREIGN KEY ("image_category_id") REFERENCES "image_categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "districts" ADD FOREIGN KEY ("province_id") REFERENCES "provinces" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "subdistricts" ADD FOREIGN KEY ("district_id") REFERENCES "districts" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
