-- ==========================================
-- V2: Multi-District Admin System Migration
-- ==========================================

-- 1. Create admins table
CREATE TABLE IF NOT EXISTS "admins" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" varchar(50) UNIQUE NOT NULL,
    "email" varchar(255) UNIQUE,
    "password_hash" varchar(255) NOT NULL,
    "full_name" varchar(100) NOT NULL,
    "phone" varchar(20),
    "role" varchar(20) NOT NULL DEFAULT 'DISTRICT_ADMIN',
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
    "created_by" integer REFERENCES "admins"("id"),
    "last_login_at" timestamp,
    "failed_login_attempts" integer DEFAULT 0,
    "locked_until" timestamp
);

-- 2. Create admin_districts junction table
CREATE TABLE IF NOT EXISTS "admin_districts" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "admin_id" integer NOT NULL REFERENCES "admins"("id") ON DELETE CASCADE,
    "district_id" integer NOT NULL REFERENCES "districts"("id") ON DELETE CASCADE,
    "assigned_at" timestamp DEFAULT CURRENT_TIMESTAMP,
    "assigned_by" integer REFERENCES "admins"("id"),
    UNIQUE("admin_id", "district_id")
);

-- 3. Create audit_logs table
CREATE TABLE IF NOT EXISTS "audit_logs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "admin_id" integer REFERENCES "admins"("id"),
    "action" varchar(50) NOT NULL,
    "entity_type" varchar(50),
    "entity_id" integer,
    "old_value" jsonb,
    "new_value" jsonb,
    "ip_address" varchar(45),
    "user_agent" text,
    "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- 4. Create password_reset_tokens table
CREATE TABLE IF NOT EXISTS "password_reset_tokens" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "admin_id" integer NOT NULL REFERENCES "admins"("id") ON DELETE CASCADE,
    "token_hash" varchar(255) NOT NULL,
    "expires_at" timestamp NOT NULL,
    "is_used" boolean DEFAULT false,
    "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- 5. Create refresh_tokens table
CREATE TABLE IF NOT EXISTS "refresh_tokens" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "admin_id" integer NOT NULL REFERENCES "admins"("id") ON DELETE CASCADE,
    "token_hash" varchar(255) NOT NULL,
    "expires_at" timestamp NOT NULL,
    "is_revoked" boolean DEFAULT false,
    "device_info" text,
    "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- 6. Add district_id to reports table
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "district_id" integer REFERENCES "districts"("id");
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "assigned_admin_id" integer REFERENCES "admins"("id");

-- 7. Add district_id to locations table
ALTER TABLE "locations" ADD COLUMN IF NOT EXISTS "district_id" integer REFERENCES "districts"("id");

-- 8. Add indexes for performance
CREATE INDEX IF NOT EXISTS "idx_reports_district_id" ON "reports"("district_id");
CREATE INDEX IF NOT EXISTS "idx_reports_assigned_admin" ON "reports"("assigned_admin_id");
CREATE INDEX IF NOT EXISTS "idx_reports_status_district" ON "reports"("report_status_id", "district_id");
CREATE INDEX IF NOT EXISTS "idx_admin_districts_admin" ON "admin_districts"("admin_id");
CREATE INDEX IF NOT EXISTS "idx_admin_districts_district" ON "admin_districts"("district_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_admin" ON "audit_logs"("admin_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_entity" ON "audit_logs"("entity_type", "entity_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_created" ON "audit_logs"("created_at");
CREATE INDEX IF NOT EXISTS "idx_locations_district_id" ON "locations"("district_id");
